/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SysNews.UI.Components;

import SysNews.EL.News;
import java.awt.Color;

/**
 *
 * @author alexq
 */
public class BigCard extends javax.swing.JPanel {

    /**
     * Creates new form BigCard
     */
    private News data;

    public BigCard() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }
    
    public void FillContent(News data){
        this.data = data;
        
        lPublishedAt.setText(data.publishedAt);
        lTitle.setText(data.title);
        imgPort.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL(data.urlToImage)
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel7 = new SysNews.UI.Swings.RoundedPanel();
        lPublishedAt = new javax.swing.JLabel();
        lTitle = new javax.swing.JLabel();
        imgPort = new SysNews.UI.Swings.ImageRoundel();

        roundedPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lPublishedAt.setBackground(new java.awt.Color(255, 255, 255));
        lPublishedAt.setForeground(new java.awt.Color(51, 51, 51));
        lPublishedAt.setText("25 Dic 1992");
        lPublishedAt.setOpaque(true);

        lTitle.setBackground(new java.awt.Color(255, 255, 255));
        lTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lTitle.setForeground(new java.awt.Color(0, 0, 0));
        lTitle.setText("Se disuelve el partido Comunista de la Republica Socialistas de ");
        lTitle.setOpaque(true);

        imgPort.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexq\\Documents\\NetBeansProjects\\News\\src\\main\\java\\SysNews\\UI\\Icons\\stalin.png")); // NOI18N
        imgPort.setRoundImg(20);

        javax.swing.GroupLayout imgPortLayout = new javax.swing.GroupLayout(imgPort);
        imgPort.setLayout(imgPortLayout);
        imgPortLayout.setHorizontalGroup(
            imgPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        imgPortLayout.setVerticalGroup(
            imgPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roundedPanel7Layout = new javax.swing.GroupLayout(roundedPanel7);
        roundedPanel7.setLayout(roundedPanel7Layout);
        roundedPanel7Layout.setHorizontalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel7Layout.createSequentialGroup()
                .addGroup(roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lPublishedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(16, 16, 16))
        );
        roundedPanel7Layout.setVerticalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel7Layout.createSequentialGroup()
                .addComponent(imgPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPublishedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SysNews.UI.Swings.ImageRoundel imgPort;
    private javax.swing.JLabel lPublishedAt;
    private javax.swing.JLabel lTitle;
    private SysNews.UI.Swings.RoundedPanel roundedPanel7;
    // End of variables declaration//GEN-END:variables
}
