/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SysNews.UI.Components;

import java.awt.Color;

/**
 *
 * @author alexq
 */
public class Card extends javax.swing.JPanel {

    /**
     * Creates new form Card
     */
    private SysNews.EL.News data;
    
    public Card() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }
    
    public void FillContent(SysNews.EL.News data){
        this.data = data;
        
        lPublishedAt.setText(data.publishedAt);
        lTitle.setText(data.title);
        imgPort.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL(data.urlToImage)
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel7 = new SysNews.UI.Swings.RoundedPanel();
        lPublishedAt = new javax.swing.JLabel();
        lTitle = new javax.swing.JLabel();
        imgPort = new SysNews.UI.Swings.ImageRoundel();

        setBackground(new java.awt.Color(255, 255, 255));

        roundedPanel7.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel7MouseClicked(evt);
            }
        });
        roundedPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lPublishedAt.setBackground(new java.awt.Color(255, 255, 255));
        lPublishedAt.setForeground(new java.awt.Color(51, 51, 51));
        lPublishedAt.setText("25 Dic 1992");
        lPublishedAt.setOpaque(true);
        roundedPanel7.add(lPublishedAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 270, 20));

        lTitle.setBackground(new java.awt.Color(255, 255, 255));
        lTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lTitle.setForeground(new java.awt.Color(0, 0, 0));
        lTitle.setText("Se disuelve el partido Comunista de la Republica Socialistas de ");
        lTitle.setOpaque(true);
        roundedPanel7.add(lTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, 25));

        imgPort.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexq\\Documents\\NetBeansProjects\\News\\src\\main\\java\\SysNews\\UI\\Icons\\stalin.png")); // NOI18N
        imgPort.setRoundImg(20);

        javax.swing.GroupLayout imgPortLayout = new javax.swing.GroupLayout(imgPort);
        imgPort.setLayout(imgPortLayout);
        imgPortLayout.setHorizontalGroup(
            imgPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        imgPortLayout.setVerticalGroup(
            imgPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        roundedPanel7.add(imgPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(roundedPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(roundedPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel7MouseClicked
        // TODO add your handling code here:
        SysNews.UI.News f = new SysNews.UI.News(this.data);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_roundedPanel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SysNews.UI.Swings.ImageRoundel imgPort;
    private javax.swing.JLabel lPublishedAt;
    private javax.swing.JLabel lTitle;
    private SysNews.UI.Swings.RoundedPanel roundedPanel7;
    // End of variables declaration//GEN-END:variables
}
