/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SysNews.UI.Components;

import java.awt.Color;

/**
 *
 * @author alexq
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel3 = new SysNews.UI.Swings.RoundedPanel();
        roundedPanel9 = new SysNews.UI.Swings.RoundedPanel();
        jLabel10 = new javax.swing.JLabel();
        roundedPanel10 = new SysNews.UI.Swings.RoundedPanel();
        jLabel11 = new javax.swing.JLabel();
        roundedPanel11 = new SysNews.UI.Swings.RoundedPanel();
        jLabel12 = new javax.swing.JLabel();
        roundedPanel12 = new SysNews.UI.Swings.RoundedPanel();
        jLabel8 = new javax.swing.JLabel();
        roundedPanel13 = new SysNews.UI.Swings.RoundedPanel();
        jLabel14 = new javax.swing.JLabel();
        roundedPanel14 = new SysNews.UI.Swings.RoundedPanel();
        jLabel13 = new javax.swing.JLabel();
        roundedPanel15 = new SysNews.UI.Swings.RoundedPanel();
        jLabel9 = new javax.swing.JLabel();

        roundedPanel3.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel9.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundedPanel9MouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(161, 125, 237));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Categorías");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel9Layout = new javax.swing.GroupLayout(roundedPanel9);
        roundedPanel9.setLayout(roundedPanel9Layout);
        roundedPanel9Layout.setHorizontalGroup(
            roundedPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roundedPanel9Layout.setVerticalGroup(
            roundedPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        roundedPanel3.add(roundedPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, 170, 40));

        roundedPanel10.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundedPanel10MouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(161, 125, 237));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Me Gusta");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel10Layout = new javax.swing.GroupLayout(roundedPanel10);
        roundedPanel10.setLayout(roundedPanel10Layout);
        roundedPanel10Layout.setHorizontalGroup(
            roundedPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel10Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roundedPanel10Layout.setVerticalGroup(
            roundedPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel10Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        roundedPanel3.add(roundedPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 112, 170, 40));

        roundedPanel11.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundedPanel11MouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(161, 125, 237));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Leer Después");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel11Layout = new javax.swing.GroupLayout(roundedPanel11);
        roundedPanel11.setLayout(roundedPanel11Layout);
        roundedPanel11Layout.setHorizontalGroup(
            roundedPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel11Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(27, 27, 27))
        );
        roundedPanel11Layout.setVerticalGroup(
            roundedPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel11Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        roundedPanel3.add(roundedPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 154, 170, 40));

        roundedPanel12.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundedPanel12MouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(161, 125, 237));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sugerencias");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel12Layout = new javax.swing.GroupLayout(roundedPanel12);
        roundedPanel12.setLayout(roundedPanel12Layout);
        roundedPanel12Layout.setHorizontalGroup(
            roundedPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        roundedPanel12Layout.setVerticalGroup(
            roundedPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel3.add(roundedPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 492, 170, 40));

        roundedPanel13.setBackground(new java.awt.Color(161, 125, 237));

        jLabel14.setBackground(new java.awt.Color(161, 125, 237));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Ayuda");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel13Layout = new javax.swing.GroupLayout(roundedPanel13);
        roundedPanel13.setLayout(roundedPanel13Layout);
        roundedPanel13Layout.setHorizontalGroup(
            roundedPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        roundedPanel13Layout.setVerticalGroup(
            roundedPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel3.add(roundedPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 534, 170, 40));

        roundedPanel14.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedPanel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundedPanel14MouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(161, 125, 237));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ajustes");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel14Layout = new javax.swing.GroupLayout(roundedPanel14);
        roundedPanel14.setLayout(roundedPanel14Layout);
        roundedPanel14Layout.setHorizontalGroup(
            roundedPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel14Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roundedPanel14Layout.setVerticalGroup(
            roundedPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel14Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        roundedPanel3.add(roundedPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 450, 170, 40));

        roundedPanel15.setBackground(new java.awt.Color(161, 125, 237));

        jLabel9.setBackground(new java.awt.Color(161, 125, 237));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Inicio");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel15Layout = new javax.swing.GroupLayout(roundedPanel15);
        roundedPanel15.setLayout(roundedPanel15Layout);
        roundedPanel15Layout.setHorizontalGroup(
            roundedPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        roundedPanel15Layout.setVerticalGroup(
            roundedPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel15Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        roundedPanel3.add(roundedPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 28, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel9MouseEntered
        roundedPanel9.setBackground(new Color(161,125,237));
        jLabel10.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel9MouseEntered

    private void roundedPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel9MouseExited
        jLabel10.setForeground(new Color(161,125,237));
        roundedPanel9.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel9MouseExited

    private void roundedPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel10MouseEntered
        roundedPanel10.setBackground(new Color(161,125,237));
        jLabel11.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel10MouseEntered

    private void roundedPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel10MouseExited
        jLabel11.setForeground(new Color(161,125,237));
        roundedPanel10.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel10MouseExited

    private void roundedPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel11MouseEntered
        roundedPanel11.setBackground(new Color(161,125,237));
        jLabel12.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel11MouseEntered

    private void roundedPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel11MouseExited
        jLabel12.setForeground(new Color(161,125,237));
        roundedPanel11.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel11MouseExited

    private void roundedPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel12MouseEntered
        roundedPanel12.setBackground(new Color(161,125,237));
        jLabel8.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel12MouseEntered

    private void roundedPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel12MouseExited
        jLabel8.setForeground(new Color(161,125,237));
        roundedPanel12.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel12MouseExited

    private void roundedPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel14MouseEntered
        roundedPanel14.setBackground(new Color(161,125,237));
        jLabel13.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel14MouseEntered

    private void roundedPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel14MouseExited
        jLabel13.setForeground(new Color(161,125,237));
        roundedPanel14.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_roundedPanel14MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private SysNews.UI.Swings.RoundedPanel roundedPanel10;
    private SysNews.UI.Swings.RoundedPanel roundedPanel11;
    private SysNews.UI.Swings.RoundedPanel roundedPanel12;
    private SysNews.UI.Swings.RoundedPanel roundedPanel13;
    private SysNews.UI.Swings.RoundedPanel roundedPanel14;
    private SysNews.UI.Swings.RoundedPanel roundedPanel15;
    private SysNews.UI.Swings.RoundedPanel roundedPanel3;
    private SysNews.UI.Swings.RoundedPanel roundedPanel9;
    // End of variables declaration//GEN-END:variables
}
